version: '3'
services:
  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx/www.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf:ro
      - ./app:/app
      - ./logs:/logs
    ports:
      - $PORT_HTTP:80
    depends_on:
      - php
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DOMAIN}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./db:/var/lib/mysql
      - ./src/db:/docker-entrypoint-initdb.d
  php:
    build: src/php-fpm
    volumes:
      - ./app:/app
    depends_on:
      - db
